// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        Background: typeof import('./src/components/common/Background.vue')['default']
        NAutoComplete: typeof import('naive-ui')['NAutoComplete']
        NAvatar: typeof import('naive-ui')['NAvatar']
        NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
        NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
        NButton: typeof import('naive-ui')['NButton']
        NCascader: typeof import('naive-ui')['NCascader']
        NConfigProvider: typeof import('naive-ui')['NConfigProvider']
        NDataTable: typeof import('naive-ui')['NDataTable']
        NDatePicker: typeof import('naive-ui')['NDatePicker']
        NDropdown: typeof import('naive-ui')['NDropdown']
        NEmpty: typeof import('naive-ui')['NEmpty']
        NForm: typeof import('naive-ui')['NForm']
        NFormItem: typeof import('naive-ui')['NFormItem']
        NGi: typeof import('naive-ui')['NGi']
        NGrid: typeof import('naive-ui')['NGrid']
        NInput: typeof import('naive-ui')['NInput']
        NLayout: typeof import('naive-ui')['NLayout']
        NLayoutContent: typeof import('naive-ui')['NLayoutContent']
        NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
        NLayoutSider: typeof import('naive-ui')['NLayoutSider']
        NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
        NMenu: typeof import('naive-ui')['NMenu']
        NMessageProvider: typeof import('naive-ui')['NMessageProvider']
        NModal: typeof import('naive-ui')['NModal']
        NScrollbar: typeof import('naive-ui')['NScrollbar']
        NSpace: typeof import('naive-ui')['NSpace']
        NSpin: typeof import('naive-ui')['NSpin']
        NSwitch: typeof import('naive-ui')['NSwitch']
        NTag: typeof import('naive-ui')['NTag']
        RegionsPicker: typeof import('./src/components/picker/RegionsPicker.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
    }
}
